// Reset is an explicit maintenance action. Never call it during normal bootstrap.
export const RESET_PHRASE = 'CANCELLA TUTTO';
const AUTO_ID = /^(wsc_(cond|autooff|oneshot|ovrflag|extras|notify)_\w+|wsc_external_profile_control|qt_timer_\w+)$/;
const HELPER_ID = /^wsc_(cond_\w+|profile_(command|active))$/;
const is404 = e => [e?.status, e?.statusCode, e?.status_code].includes(404);

async function statesNow(hass) {
  const states = await hass.connection.sendMessagePromise({ type: 'get_states' });
  if (!Array.isArray(states)) throw new Error('Invalid state response');
  return { ...hass, states: Object.fromEntries(states.map(s => [s.entity_id, s])) };
}

export async function prepareReset(card, Base) {
  const hass = card._hass;
  if (!Base._isAdmin(hass)) throw new Error('Administrator required');
  const config = await hass.connection.sendMessagePromise({ type: 'get_config' });
  if (config?.state !== 'RUNNING') throw new Error('Home Assistant is not running');
  const snapshot = await statesNow(hass);
  const data = await Base._sharedGet(snapshot, 'weekly_schedule_card');
  if (!data) throw new Error(card.t('reset.unreadable'));
  if (data.resetPending) return data.resetPending;
  const registry = await hass.connection.sendMessagePromise({ type: 'config/entity_registry/list' });
  const helperConfig = await hass.connection.sendMessagePromise({ type: 'input_text/list' });
  if (!Array.isArray(registry) || !Array.isArray(helperConfig)) throw new Error('Invalid registry response');
  const timers = await Base._sharedGet(snapshot, 'quick_timer_card');
  if (!timers && helperConfig.some(h => /^wsc_qt_store_/.test(h.id))) throw new Error(card.t('reset.unreadable'));
  if (timers && (!timers.timers || typeof timers.timers !== 'object' || Array.isArray(timers.timers)))
    throw new Error('Invalid Quick Timer data');

  const scheduleIds = new Set((data.profiles || []).flatMap(p => p.schedules || []));
  for (const p of data.profiles || []) for (const link of p.scheduleLinks || [])
    if (link.autoChildId) scheduleIds.add(link.autoChildId);
  for (const t of Object.values(timers?.timers || {}))
    for (const id of t.scheduleIds || []) scheduleIds.add(id);
  // Include identifiable generated schedules even when a profile link was lost.
  for (const s of Object.values(snapshot.states)) {
    if (!s.entity_id.startsWith('switch.schedule_')) continue;
    const tags = s.attributes?.tags || [];
    if (card._isQuickTimerSchedule(s) || tags.includes('weekly_schedule_auto')
      || s.attributes?.actions?.[0]?.service_data?.name === 'WSC conditional v1') scheduleIds.add(s.entity_id);
  }
  if ([...scheduleIds].some(id => !/^switch\.schedule_\w+$/.test(id))) throw new Error('Invalid schedule ID');

  // Only generated automation configs: namespace AND generator description.
  // The registry also covers disabled/renamed automation entities.
  const automations = [];
  for (const entry of registry) {
    if (entry.platform !== 'automation' || !AUTO_ID.test(entry.unique_id)) continue;
    let cfg;
    try { cfg = await hass.callApi('GET', `config/automation/config/${entry.unique_id}`); }
    catch (e) { if (is404(e)) continue; throw e; }
    if (!/^(Auto-generated by Weekly Schedule Card|WSC conditional controller v\d+)/.test(cfg.description || '')) continue;
    automations.push({ id: entry.unique_id, entityId: entry.entity_id, config: cfg });
  }
  // Tracked controllers must be accounted for; a failed/ambiguous inventory is not
  // permission to delete their parent and leave an active controller behind.
  const tracked = (data.profiles || []).flatMap(p => (p.scheduleLinks || []).flatMap(l =>
    ['condAutoId', 'autoOffAutoId', 'oneShotAutoId', 'extrasAutoId', 'notifyAutoId', 'overrideFlagAutoId'].map(k => l[k]).filter(Boolean)));
  for (const t of Object.values(timers?.timers || {})) if (t.autoId) tracked.push(t.autoId);
  for (const id of tracked) {
    if (!AUTO_ID.test(id)) throw new Error(`Unrecognized controller: ${id}`);
    if (!automations.some(a => a.id === id) && registry.some(e => e.platform === 'automation' && e.unique_id === id))
      throw new Error(`Controller ownership is ambiguous: ${id}`);
  }
  const helpers = helperConfig.filter(h => HELPER_ID.test(h.id)).map(h => {
    const entityId = registry.find(e => e.platform === 'input_text' && e.unique_id === h.id)?.entity_id || `input_text.${h.id}`;
    return { id: h.id, entityId, config: h, state: snapshot.states[entityId]?.state ?? null };
  });
  for (const id of scheduleIds) if (!snapshot.states[id] && registry.some(e => e.entity_id === id))
    throw new Error(`Schedule is disabled or unavailable in the state machine: ${id}`);
  const schedules = [...scheduleIds].sort().filter(id => snapshot.states[id]).map(id => JSON.parse(JSON.stringify(snapshot.states[id])));
  const ignored = Object.keys(snapshot.states).filter(id => id.startsWith('switch.schedule_') && !scheduleIds.has(id)).sort();
  return {
    version: 1, id: `reset_${Date.now()}_${Math.random().toString(36).slice(2)}`,
    original: data, timers, automations, helpers, schedules, ignored,
  };
}

async function verifyTargets(hass, plan, changed) {
  // A preview is not authorization to delete a config edited since export.
  // Missing objects are expected when resuming an interrupted reset.
  for (const a of plan.automations) {
    let config;
    try { config = await hass.callApi('GET', `config/automation/config/${a.id}`); }
    catch (e) { if (is404(e)) continue; throw e; }
    if (JSON.stringify(config) !== JSON.stringify(a.config)) throw new Error(changed);
  }
  const fields = ['actions', 'timeslots', 'weekdays', 'repeat_type', 'tags'];
  for (const s of plan.schedules) {
    const now = hass.states[s.entity_id];
    if (now && fields.some(k => JSON.stringify(now.attributes?.[k]) !== JSON.stringify(s.attributes?.[k])))
      throw new Error(changed);
  }
  const helpers = await hass.connection.sendMessagePromise({ type: 'input_text/list' });
  if (!Array.isArray(helpers)) throw new Error('Invalid helper response');
  for (const h of plan.helpers) {
    const now = helpers.find(x => x.id === h.id);
    if (now && JSON.stringify(now) !== JSON.stringify(h.config)) throw new Error(changed);
  }
}

export async function executeReset(card, Base, plan, phrase) {
  if (phrase !== RESET_PHRASE || !Base._isAdmin(card._hass)) throw new Error('Reset not confirmed');
  if (plan?.version !== 1 || !/^reset_\w+$/.test(plan.id)) throw new Error('Invalid reset plan');
  if (plan.schedules.some(s => !/^switch\.schedule_\w+$/.test(s.entity_id))
    || plan.automations.some(a => !AUTO_ID.test(a.id) || !/^automation\.\w+$/.test(a.entityId))
    || plan.helpers.some(h => !HELPER_ID.test(h.id))) throw new Error('Invalid reset target');
  let hass = await statesNow(card._hass);
  const current = await Base._sharedGet(hass, 'weekly_schedule_card');
  if (!current || (current.resetPending ? current.resetPending.id !== plan.id : JSON.stringify(current) !== JSON.stringify(plan.original)))
    throw new Error(card.t('reset.changed'));
  const qt = await Base._sharedGet(hass, 'quick_timer_card');
  if (!current.resetPending && JSON.stringify(qt) !== JSON.stringify(plan.timers)) throw new Error(card.t('reset.changed'));
  await verifyTargets(hass, plan, card.t('reset.changed'));
  const options = { resetId: plan.id };
  if (!Base._resetSessions) Base._resetSessions = new WeakSet();
  Base._resetSessions.add(hass.connection);
  // Persist the complete inventory before deleting anything. Failure keeps this
  // record for explicit resume even if the browser closes or HA restarts.
  const pending = { ...plan.original, resetPending: plan };
  try {
    await Base._sharedSet(hass, 'weekly_schedule_card', pending, options);
  } catch (e) {
    Base._resetSessions.delete(hass.connection);
    throw e;
  }
  card._storageData = pending;
  try {
    hass = await statesNow(card._hass);
    // Stop every generated controller (including running actions) before removing
    // schedules. Do NOT invoke timer cancel, end actions, or device restore services.
    for (const a of plan.automations) if (hass.states[a.entityId]) {
      if (hass.states[a.entityId].attributes?.id !== a.id) throw new Error(`Controller changed: ${a.entityId}`);
      await hass.callService('automation', 'turn_off', { entity_id: a.entityId, stop_actions: true });
    }
    for (const a of plan.automations) {
      try { await hass.callApi('DELETE', `config/automation/config/${a.id}`); }
      catch (e) { if (!is404(e)) throw e; }
    }
    hass = await statesNow(card._hass);
    for (const s of plan.schedules) if (hass.states[s.entity_id])
      await hass.callService('scheduler', 'remove', { entity_id: s.entity_id });
    const helpers = await hass.connection.sendMessagePromise({ type: 'input_text/list' });
    if (!Array.isArray(helpers)) throw new Error('Invalid helper response');
    for (const h of plan.helpers) {
      if (helpers.some(x => x.id === h.id))
        await hass.connection.sendMessagePromise({ type: 'input_text/delete', input_text_id: h.id });
      Base._createdHelpers?.delete(h.entityId);
      Base._createdHelpers?.delete(`input_text.${h.id}`);
    }
    if (plan.timers) await Base._sharedSet(hass, 'quick_timer_card', { timers: {} }, options);
    // Leave valid empty canonical storage so old per-user data cannot be migrated
    // again. Storage helpers are reusable infrastructure, not orphaned runtime data.
    await hass.connection.sendMessagePromise({ type: 'frontend/set_user_data', key: 'weekly_schedule_card', value: null });
    const clean = { groups: [], profiles: [{ id: 'default', name: 'Default', exclusive: true, groups: [], schedules: [], scheduleLinks: [] }], activeProfiles: [], resetAt: new Date().toISOString() };
    await Base._sharedSet(hass, 'weekly_schedule_card', clean, options);
    Base._resetSessions.delete(hass.connection);
    card._storageData = clean;
    card._selectedProfileId = 'default';
    card._externalProfileControlSignature = null;
    window.dispatchEvent(new CustomEvent('wsc-storage-changed', { detail: { source: card, data: clean } }));
    return clean;
  } catch (e) {
    // Keep the session paused and persisted inventory intact. Resume is explicit.
    throw new Error(`${card.t('reset.failed')} ${e.message || e}`);
  }
}
